name: Create release and semver tag
description: A GitHub Action which automatically creates releases and semver tags
author: Kevin Königseder

inputs:
  github-token:
    description: GitHub token
    required: true
    default: ""

  base-branch:
    description: The base branch to create the release from
    required: false
    default: "master"

  major-release-tag:
    description: Name of the tag that is used to determine if it's a major release
    required: false
    default: "major change"

  minor-release-tag:
    description: Name of the tag that is used to determine if it's a minor release
    required: false
    default: "minor change"

  patch-release-tag:
    description: Name of the tag that is used to determine if it's a patch release
    required: false
    default: "patch change"

outputs:
  new-release-tag:
    description: The newly created semver tag

runs:
  using: node16
  main: dist/index.js
