name: Create release and SemVer tag
description: A GitHub Action which automatically creates releases and SemVer tags
author: Kevin Königseder
branding:
  icon: tag
  color: purple

inputs:
  github-token:
    description: GitHub token
    required: true
    default: ""

  release-body:
    description: The release's body
    required: false

  base-branch:
    description: The base branch to create the release from
    required: false
    default: "master"

  semver-prefix:
    description: A prefix like 'v' in front of the version number
    required: false
    default: ""

  semver-start-version:
    description: If there is no release so far, start with this
    required: false
    default: "1.0.0"

  major-release-label:
    description: Name of the label that is used to determine if it's a major release
    required: false
    default: "major change"

  minor-release-label:
    description: Name of the label that is used to determine if it's a minor release
    required: false
    default: "minor change"

  patch-release-label:
    description: Name of the label that is used to determine if it's a patch release
    required: false
    default: "patch change"

outputs:
  new-release-tag:
    description: The newly created semver tag

  major-release-label:
    description: Name of the label that is used to determine if it's a major release

  minor-release-label:
    description: Name of the label that is used to determine if it's a minor release

  patch-release-label:
    description: Name of the label that is used to determine if it's a patch release

runs:
  using: node16
  main: dist/index.js
