name: Build and compile action

on:
  pull_request:
    paths:
      - src/**.ts
  workflow_dispatch:

jobs:
  compile-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile TypeScript to JavaScript
        run: |
          npm install && npm run prestart

      - name: Commit compiled version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist
