name: Create new release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        id: create-release
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-body: ${{ github.event.pull_request.body }}
          base-branch: master
          semver-prefix: v

      - name: Output result (new release)
        if: ${{ steps.create-release.outputs.new-release-tag != '' }}
        env:
          NEW_RELEASE_TAG: ${{ steps.create-release.outputs.new-release-tag }}
        run: |
          printf "### :heavy_check_mark: Created new release for this PR\n\nNew release: \`$NEW_RELEASE_TAG\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Output result (no new release)
        if: ${{ steps.create-release.outputs.new-release-tag == '' }}
        env:
          MAJOR_RELEASE_LABEL: ${{ steps.create-release.outputs.major-release-label }}
          MINOR_RELEASE_LABEL: ${{ steps.create-release.outputs.minor-release-label }}
          PATCH_RELEASE_LABEL: ${{ steps.create-release.outputs.patch-release-label }}
        run: |
          printf "### :x: No new release was created for this PR\n\nIn order to create a release set a valid label:\n\n- Major release: \`$MAJOR_RELEASE_LABEL\`\n- Minor release: \`$MINOR_RELEASE_LABEL\`\n- Patch release: \`$PATCH_RELEASE_LABEL\`" >> "$GITHUB_STEP_SUMMARY"
