name: Build and release

on:
  pull_request:
  workflow_dispatch:

jobs:
  compile-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile TypeScript to JavaScript
        run: |
          npm install && npm run build && npm run prestart

      - name: Commit compiled version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist

  create-release:
    runs-on: ubuntu-latest
    needs: compile-action

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: develop
